# Generated by Django 4.0.5 on 2022-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cart_customer_product_shippingaddress_cartitems_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=12)),
                ('people', models.CharField(max_length=12)),
                ('message', models.TextField()),
            ],
        ),
    ]
